Feature1向保护分支feature2合并
tanghongtanghong/ai-v2 pull request #4
Opened 2021-01-14 10:25 UTC by tanghongtanghong

合并。。。
。。哈哈哈哈

2021-01-14 10:27 UTC, shinely05 requested changes
more infos

2021-01-14 10:27 UTC, shinely05 commented on 0114file
> +jjjjj
不不不不不不不

2021-01-14 11:43 UTC, tanghongtanghong reviewed
猜猜猜

2021-01-25 03:13 UTC, tanghongtanghong reviewed
1

2021-01-25 03:15 UTC, tanghongtanghong reviewed
213

2021-01-25 03:15 UTC, tanghongtanghong commented on 0114file
> +hhhhh
3223

2021-01-25 03:15 UTC, tanghongtanghong commented on 0114file
> +hhhhh
ttt

2021-01-25 03:20 UTC, tanghongtanghong reviewed
test

2021-01-25 03:20 UTC, tanghongtanghong commented on 0114file
> +this is a new file
呃呃呃呃

2021-01-25 03:35 UTC, tanghongtanghong reviewed
OK

2021-01-25 03:35 UTC, tanghongtanghong commented on test0113
> +//this is a file
这一行有问题

2021-01-25 03:35 UTC, tanghongtanghong commented on test0113
> +is
这个参数要改一下

2021-01-25 03:35 UTC, tanghongtanghong commented on test0113
> +do new change
这个还有问题

2021-01-25 03:35 UTC, tanghongtanghong commented on test0113
> +jajajajaj
这个也有问题

2021-01-25 03:35 UTC, tanghongtanghong commented on test0113
> +//this is a file
第一行、第二行代码的评论

2021-01-25 03:35 UTC, tanghongtanghong commented on test0113
> +//this is a file
呃呃呃

2021-01-25 03:35 UTC, tanghongtanghong commented on test0113
> +jajajajaj
纯纯粹粹

2021-01-25 03:35 UTC, tanghongtanghong commented on 0114file
> +
吃吃

2021-01-25 03:35 UTC, tanghongtanghong commented on 0114file
> +hhhhh
猜猜猜

2021-01-25 05:33 UTC, tanghongtanghong commented on 0114file
> +jjjjj
啦啦啦

2021-01-25 05:33 UTC, tanghongtanghong commented
对这个PR进行评论

2021-01-26 10:01 UTC, tanghongtanghong reviewed
嘻嘻

2021-01-26 10:01 UTC, tanghongtanghong commented on 0114file
> +this is a new file
做了一个评论

2021-01-26 10:02 UTC, tanghongtanghong commented on 0114file
> +this is a new file
休息休息

2021-01-26 10:20 UTC, tanghongtanghong commented on 0114file
> +
add single comment

2021-02-01 12:36 UTC, closed without merging